# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image:
  file: .docker/Dockerfile

# Command to start on workspace startup (optional)
tasks:
  - init: cd angularApp &&
          npm install --silent &&
          npm start

  - command: cd newApi && dotnet run

# Ports to expose on workspace startup (optional)
ports:
  - port: 4200
    onOpen: open-preview
  - port: 5000

vscode:
  extensions:
    - ms-vscode.csharp@1.21.7:63Epcq/w+Vl8tIwYMHyrXg==

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: false
    # enable for all branches in this repo (defaults to false)
    branches: true